export const ALL_EXCHANGES = 'ALL_EXCHANGES'
export const EXCHANGE_BY_ID = 'EXCHANGE_BY_ID'

export const LOADING_MARKETS = 'LOADING_MARKETS'
export const FAILED_MARKETS = 'FAILED_MARKETS'
export const LOAD_MARKETS = 'LOAD_MARKETS'
export const LOAD_PAIR = 'LOAD_PAIR'

export const LOADING_TRADES = 'LOADING_TRADES'
export const FAILED_TRADES = 'FAILED_TRADES'
export const LOAD_TRADES = 'LOAD_TRADES'

export const CLEAR_STATE = 'CLEAR_STATE'
